POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhYmVseTIyNSIsImlkIjoiNjM1MmI5NmQ5NTU3M2U4NjM1OTgxYzhlIiwiaWF0IjoxNjY2NDM5ODczfQ.xD9vrtSRJzaqDYMU-XjMbsMkBJaW8RFTamjjtdKZAGM

{
    "title": "DEV BLOG",
    "author": "Daydy Dev",
    "url": "www.dev.blog",
    "userId": "6352b96d95573e8635981c8e",
    "likes": 8
}